- name: Demo of varibles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print variables
      debug:
        msg: Hello{{URL_PLAY}}

    - name: print varibale again
      debug:
        msg: Good{{URL_PLAY}}


#Task level variables

- name: Print task vars
  hosts: all
  tasks:
    - name: Print tasks
      debug:
        msg: Hello{{URL_TASK1}}

      VARS:
        URL_TASK1: task1.example.com



