- name: Demo of vars on Play level
  hosts: all
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print Variable Value
      debug:
        msg: Hello {{ URL_PLAY }}

    - name: Print Variable again
      debug:
        msg: Bye {{ URL_PLAY }}