- name: Demo of varibles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print variables
      debug:
        msg: Hello{{URL_PLAY}}

    - name: print varibale again
      debug:
        msg: Good{{URL_PLAY}}
